// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
..............fffcc.................
..............fbbddc................
...............fbbddc...............
ccc............fcbbccf..............
cbbcc.........ffccccccffffff........
.cbbdc.....fffcbbbbbbbbbbbbbff......
.fbbddc..ffcccbbbbcbcbbbbbbbbbff....
..fbbdfffcccccbbbcbcbbffbbbbbcbf....
..fcbbbcccccccbbbcbcb1ff1111bbbf....
..fccbcccccccccbbbbbb11111111bf.....
.fcbbfffccccccccbbbb11cc33cccf......
.fbbf...cbdbcccccbbb111c131cf.......
fbbf.....ccdddddfbbbc111c33f........
fff........ccddfbbdbf1111ff.........
.............cfbbdbfccccc...........
..............fffff.................
`, img`
..............fffcc.................
..............fbbddc................
...............fbbddc...............
...............fcbbccffffff.........
..............ffcccbbbbbbbbfff......
ccccc......fffcbbbbbbbbbbbbbbbf.....
cbbbdc...ffcccbbbbcbcbffbbbbbcb.....
.cbbddcffcccccbbbcbcbbff1111bbb.....
..fbbdbcccccccbbbcbcb11111111bf.....
..fcbbcccccccccbbbbbb11c33cccf......
..fccbffccccccccbbbb11cc131cf.......
.fcbbf..cbdbcccccbbb1111c33f........
.fbbf....ccdddddfbbbc1111ff.........
fbbf.......ccddfbbdbf1ccc...........
fff..........cfbbdbfcc..............
..............fffff.................
`, img`
.............fffcc..................
.............fbbddc.................
..............fbbddfffffffff........
..............fcbcfbbbbbbbbbf.......
...........ffffccbbffb111cbbf.......
ccccc....ffcccbbbbbff111111bf.......
cbbbdc..fccccbbcbcbb1133cc1f........
.cbbddcfcccccbcbcbbb1c131ccf........
..fbbdbccccccbcbcbbb111111f.........
..fcbbccccccccbbbbb1111111f.........
..fccbffcccccccbbbb111111f..........
.fcbbf.cbdbcccccbbbc1111c...........
.fbbf...cddddddfbbbc11cc............
fbbf.....ccdddfbbdbffc..............
fff........ccfbbdbf.................
.............fffff..................
`, img`
...........fffcc....................
...........fbbbbcfffffffff..........
............fbfffbbbbbbbbbf.........
............ffbbbbffb111bbf.........
..........ffcbbbbbff11111bf.........
.........fcccbcbcbb11cccc1f.........
ccccc...fcccbcbcbbb1c1c1cf..........
cbbddccfccccbcbcbbb1333c............
.ccbddbcccccbbbbbbb1c333c...........
..ccbbcccccccbbbbb11c133c...........
..fccbffccccccbbbb111c31cc..........
..fccf.cbbcccccbbbc111111c..........
.fcbbf..cdddddfbbbc1111cc...........
.fbbf....cdddfbbdbffccc.............
fbbf......ccfbbdbf..................
fff.........fffff...................
`, img`
..........fffcc...fffffff...........
..........fbbbbcffbbbbbbbf..........
...........fbffbbbbb111bbf..........
...........ffbbbbff11111bf..........
.........ffcbbbbbff1cccc1f..........
........fcccbcbcbb1c1c1cff..........
ccccc..fcccbcbcbbb1333ccf...........
cbbddcfccccbcbcbbb1c333c............
.ccbddcccccbbbbbbb1c333c............
..ccbbccccccbbbbb11c333c............
..fccbfccccccbbbb11c133cc...........
..fccfcbbcccccbbbc11c31cc...........
.fcbbf.cdddddfbbbc111111c...........
.fbbf...cdddfbbdbf1111cc............
fbbf.....ccfbbdbfffccc..............
fff........fffff....................
`, img`
....................................
....................................
....................................
...............ffffcc...............
...............fbbbddc..............
................fbbbddcffffff.......
ccccc.......fffcbbbbbbbbbbbbbff.....
cbbbdc....ffcccbbbbbcbcbbbbbbbbff...
.cbbddcfffcccccbbbbcbbcbbbbbbbbbbf..
..fbbdbccccccccbbbbcbcbbbbbbbbbbcbf.
..fcbbccccccccccbbbbbcbbfffbbbbbbbf.
..fccbffcbcccccccbbbbcbbfff1111bbff.
.fcbbf..ccbbbccccccbbbb111111111ff..
fbbff.....cccbddfbbbdb111ccccccc....
fff..........ccfbbbdbfcccccc........
...............ffffff...............
`];
            case "myAnim0":
            case "anim2":return [img`
..............fffcc.................
..............fbbddc................
...............fbbddc...............
ccc............fcbbccf..............
cbbcc.........ffccccccffffff........
.cbbdc.....fffcbbbbbbbbbbbbbff......
.fbbddc..ffcccbbbbcbcbbbbbbbbbff....
..fbbdfffcccccbbbcbcbbffbbbbbcbf....
..fcbbbcccccccbbbcbcb1ff1111bbbf....
..fccbcccccccccbbbbbb11111111bf.....
.fcbbfffccccccccbbbb11cc33cccf......
.fbbf...cbdbcccccbbb111c131cf.......
fbbf.....ccdddddfbbbc111c33f........
fff........ccddfbbdbf1111ff.........
.............cfbbdbfccccc...........
..............fffff.................
`, img`
..............fffcc.................
..............fbbddc................
...............fbbddc...............
...............fcbbccffffff.........
..............ffcccbbbbbbbbfff......
ccccc......fffcbbbbbbbbbbbbbbbf.....
cbbbdc...ffcccbbbbcbcbffbbbbbcb.....
.cbbddcffcccccbbbcbcbbff1111bbb.....
..fbbdbcccccccbbbcbcb11111111bf.....
..fcbbcccccccccbbbbbb11c33cccf......
..fccbffccccccccbbbb11cc131cf.......
.fcbbf..cbdbcccccbbb1111c33f........
.fbbf....ccdddddfbbbc1111ff.........
fbbf.......ccddfbbdbf1ccc...........
fff..........cfbbdbfcc..............
..............fffff.................
`, img`
.............fffcc..................
.............fbbddc.................
..............fbbddfffffffff........
..............fcbcfbbbbbbbbbf.......
...........ffffccbbffb111cbbf.......
ccccc....ffcccbbbbbff111111bf.......
cbbbdc..fccccbbcbcbb1133cc1f........
.cbbddcfcccccbcbcbbb1c131ccf........
..fbbdbccccccbcbcbbb111111f.........
..fcbbccccccccbbbbb1111111f.........
..fccbffcccccccbbbb111111f..........
.fcbbf.cbdbcccccbbbc1111c...........
.fbbf...cddddddfbbbc11cc............
fbbf.....ccdddfbbdbffc..............
fff........ccfbbdbf.................
.............fffff..................
`, img`
...........fffcc....................
...........fbbbbcfffffffff..........
............fbfffbbbbbbbbbf.........
............ffbbbbffb111bbf.........
..........ffcbbbbbff11111bf.........
.........fcccbcbcbb11cccc1f.........
ccccc...fcccbcbcbbb1c1c1cf..........
cbbddccfccccbcbcbbb1333c............
.ccbddbcccccbbbbbbb1c333c...........
..ccbbcccccccbbbbb11c133c...........
..fccbffccccccbbbb111c31cc..........
..fccf.cbbcccccbbbc111111c..........
.fcbbf..cdddddfbbbc1111cc...........
.fbbf....cdddfbbdbffccc.............
fbbf......ccfbbdbf..................
fff.........fffff...................
`, img`
..........fffcc...fffffff...........
..........fbbbbcffbbbbbbbf..........
...........fbffbbbbb111bbf..........
...........ffbbbbff11111bf..........
.........ffcbbbbbff1cccc1f..........
........fcccbcbcbb1c1c1cff..........
ccccc..fcccbcbcbbb1333ccf...........
cbbddcfccccbcbcbbb1c333c............
.ccbddcccccbbbbbbb1c333c............
..ccbbccccccbbbbb11c333c............
..fccbfccccccbbbb11c133cc...........
..fccfcbbcccccbbbc11c31cc...........
.fcbbf.cdddddfbbbc111111c...........
.fbbf...cdddfbbdbf1111cc............
fbbf.....ccfbbdbfffccc..............
fff........fffff....................
`, img`
....................................
....................................
....................................
...............ffffcc...............
...............fbbbddc..............
................fbbbddcffffff.......
ccccc.......fffcbbbbbbbbbbbbbff.....
cbbbdc....ffcccbbbbbcbcbbbbbbbbff...
.cbbddcfffcccccbbbbcbbcbbbbbbbbbbf..
..fbbdbccccccccbbbbcbcbbbbbbbbbbcbf.
..fcbbccccccccccbbbbbcbbfffbbbbbbbf.
..fccbffcbcccccccbbbbcbbfff1111bbff.
.fcbbf..ccbbbccccccbbbb111111111ff..
fbbff.....cccbddfbbbdb111ccccccc....
fff..........ccfbbbdbfcccccc........
...............ffffff...............
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
